### ISSUE TITLE
Can't run invoke command

### ISSUE THREAD

**Issue by jeffswillbejeffs** [merill/m365-gender-pronoun-kit#1]
![image](https://user-images.githubusercontent.com/48928251/125991868-9a940597-34fa-42d0-8d32-5c943be608cd.png)

So I know I have the correct script and updated all the values and even updated PnP to V16 but still no luck would love some insight.

**Comment by merill** [comment]
Apologies for the delay. Please see https://github.com/merill/m365-gender-pronoun-kit/issues/5
