### ISSUE TITLE
ExtensionAttribute1 not showing on Profile card in Outlook (but showing in Delve)

### ISSUE THREAD

**Issue by Oslaf85** [merill/m365-gender-pronoun-kit#10]
Hello there and thank you for this project which I almost finished implementing for a customer.

One issue I've come across is that in their AD-synced environment, the Custom Pronoun set by the end users in Delve does not show on the Outlook contact card.

I know your original project didn't include an AD-Synced scenario so I implemented @CabbageandBean's scipt here (https://github.com/merill/m365-gender-pronoun-kit/issues/6#issuecomment-1237012893) so the Attribute copies from Delve to the AD user on extensionattribute1, and AAD Connect then transfers it back up to the cloud where it ends up in Azure AD as a user extension attribute with key "extension_ac9d3aedab764f31bcc7ca4890d843ce_extensionAttribute1".

Does the Set-ProfileCardPronoun.ps1 script need to be amended in this case, to fetch that value rather than extensionattribute1 ?

Thanks!

**Comment by merill** [comment]
Hey @Oslaf85 if you write it to the extensionAttribute1 in on-prem AD it should sync directly to the field. You don't need to run Set-ProfileCardPronoun. The value will then be available for the profile card to display. Are you not seeing the values in the profile card?

Graph API doesn't provide a way view these extension attributes directly but if you open the user in Exchange you will be able to see the values have been synced.

**Comment by CabbageandBean** [comment]
> Hello there and thank you for this project which I almost finished implementing for a customer.
> 
> One issue I've come across is that in their AD-synced environment, the Custom Pronoun set by the end users in Delve does not show on the Outlook contact card.
> 
> I know your original project didn't include an AD-Synced scenario so I implemented @CabbageandBean's scipt here ([#6 (comment)](https://github.com/merill/m365-gender-pronoun-kit/issues/6#issuecomment-1237012893)) so the Attribute copies from Delve to the AD user on extensionattribute1, and AAD Connect then transfers it back up to the cloud where it ends up in Azure AD as a user extension attribute with key "extension_ac9d3aedab764f31bcc7ca4890d843ce_extensionAttribute1".
> 
> Does the Set-ProfileCardPronoun.ps1 script need to be amended in this case, to fetch that value rather than extensionattribute1 ?
> 
> Thanks!

Hello, profile card implementation doesn't work here either but that wasn't my primary focus for the implementation. We wanted the pronouns in our Display Names so a script runs on my DC to appended the display name with ext att 1. Sorry I cant help here.

**Comment by Oslaf85** [comment]
> Hello, profile card implementation doesn't work here either but that wasn't my primary focus for the implementation. We wanted the pronouns in our Display Names so a script runs on my DC to appended the display name with ext att 1. Sorry I cant help here.

Thanks for the reply. I see, I think that's what I'll end up doing for our customer as they want the pronouns more prominently displayed. Does your script basically just check that the ext att 1 is not null, and appends it to the end of their display name?

**Comment by CabbageandBean** [comment]
> > Hello, profile card implementation doesn't work here either but that wasn't my primary focus for the implementation. We wanted the pronouns in our Display Names so a script runs on my DC to appended the display name with ext att 1. Sorry I cant help here.
> 
> Thankd for the reply. I see, I think that's what I'll end up doing for our customer as they want the pronouns more prominently displayed. Does your script basically just check that the ext att 1 is not null, and appends it to the end of their display name?

That's exactly what it does. Nothing fancy. Just scheduled it on the dc along side the pronoun sync script.

**Comment by Oslaf85** [comment]
> Hey @Oslaf85 if you write it to the extensionAttribute1 in on-prem AD it should sync directly to the field. You don't need to run Set-ProfileCardPronoun. The value will then be available for the profile card to display. Are you not seeing the values in the profile card?
> 
> Graph API doesn't provide a way view these extension attributes directly but if you open the user in Exchange you will be able to see the values have been synced.

Hey @merill thanks for replying so quickly. I had already run Set-ProfileCardPronoun before I realised that in an AD-synced environment I didn't need to.

And I think I was confusing myself with a test account where the User Logon Name on-prem didn't exactly match the email address for the contact I was looking at in Outlook. I am not sure what happened there, but when I added the correct proxyaddresses on-prem AD and re-run a Delta sync, I then checked the Profile card in Outlook again for the same user and the Pronoun field was there!

Thanks for the project and your help, I'll close the issue now.
Thanks @CabbageandBean for your suggestions as well.
