### ISSUE TITLE
Replaced by built-in feature?

### ISSUE THREAD

**Issue by pl4nty** [merill/m365-gender-pronoun-kit#12]
Per the note in the readme, has this project been replaced by [built-in pronouns on profile cards](https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/turn-pronouns-on-or-off)?

**Comment by merill** [comment]
Yes. I would recommend using the out of the box solution.

**Comment by pl4nty** [comment]
Thanks for this your great projects @merill :)
I'll look at migrating to the built-in version
