### ISSUE TITLE
Documentation for editing Azure Active Directory User Profile custom attribute in custom SharePoint page or PowerApp?

### ISSUE THREAD

**Issue by KeithGillette** [merill/m365-gender-pronoun-kit#2]
Thanks for providing this script. The README states, "Alternative options to edit the user profile can be implemented including a PowerApp or a custom SharePoint page to directly update the Pronoun attribute in Azure Active Directory." Where may I find documentation for implementing either of those options?

**Comment by merill** [comment]
@KeithGillette I haven't had a chance to build this out yet. If you do end up building something it will be good to share it here.

**Comment by KeithGillette** [comment]
Thanks, @merill. I'll certainly share any solution I may come up with. If you can provide pointers to any general API documentation for authenticating users and working with custom attributes in AAD from PowerApps or SharePoint or in general, that would be helpful in getting started.

**Comment by merill** [comment]
FYI Microsoft 365 may soon be getting an OOTB feature to show gender profile so you might want to hold off on building a custom solution just yet.

**Comment by KeithGillette** [comment]
That's great news, @merill. Is this on a roadmap where we can track progress for release?
