### ISSUE TITLE
Can't run invoke-pronounsync

### ISSUE THREAD

**Issue by rhelfang** [merill/m365-gender-pronoun-kit#5]
I can't seem to get this cmdlet to run. It's looking for a certificate but I can't locate it. Any thoughts/advice? I'm not terribly experienced with PnP.

![image](https://user-images.githubusercontent.com/104470509/166075957-0e6bc15f-1dc7-48ab-953a-cc7f993b6279.png)

**Comment by merapc** [comment]
look for the .pfx name in the folder and change it appropriatly. Also, path should be in quotes '.\PnPpowershell.pfx'

**Comment by merill** [comment]
Thanks for helping out @merapc
